version: '3.3'

services:
  web:
    restart: always
    container_name: backend
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
    env_file:
      - .env


  redis:
    image: redis:7-alpine
